version: "3.7"
services:
  api:
    build: ./api
    ports:
      - 3001:3001
    depends_on:
      - db
  client:
    build: ./client
    ports:
      - 3000:80
  db:
    image: mongo
    ports:
      - 27017:27017