version: "3.7"
services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    ports:
      - 3001:3001
    depends_on:
      - db
    volumes:
      - /app/node_modules
      - ./api:/app
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./client:/app
    stdin_open: true
  db:
    image: mongo
    ports:
      - 27017:27017